import React,{useMemo,useState} from "react";
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {splitByExact,splitByPercent,splitByShares} from "@family-expense/financial-engine";

type Mode="EQUAL"|"EXACT"|"PERCENTAGE"|"SHARES";
const people=[{id:"me",name:"You"},{id:"mom",name:"Mum"},{id:"dad",name:"Dad"},{id:"sibling",name:"Sibling"}];

export function ExpenseComposerScreen(){
 const [amount,setAmount]=useState(""); const [description,setDescription]=useState(""); const [mode,setMode]=useState<Mode>("EQUAL"); const [selected,setSelected]=useState(people.map(p=>p.id));
 const total=BigInt(amount||"0");
 const allocations=useMemo(()=>{if(total<=0n||!selected.length)return []; if(mode==="EQUAL"){const base=total/BigInt(selected.length),rem=total%BigInt(selected.length);return selected.map((id,i)=>({userId:id,amountMinor:base+(BigInt(i)<rem?1n:0n)}));} if(mode==="PERCENTAGE")return splitByPercent(total,selected.map((id,i)=>({userId:id,percentage:i===0?100-(selected.length-1)*Math.floor(100/selected.length):Math.floor(100/selected.length)}))); if(mode==="SHARES")return splitByShares(total,selected.map(id=>({userId:id,shares:1n}))); return selected.map(id=>({userId:id,amountMinor:0n}));},[total,mode,selected]);
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Add expense</Text><TextInput value={description} onChangeText={setDescription} placeholder="What was this for?" style={s.input}/><Text style={s.amountLabel}>₹</Text><TextInput value={amount} onChangeText={v=>setAmount(v.replace(/\\D/g,""))} keyboardType="number-pad" placeholder="0" style={s.amount}/><Text style={s.section}>Paid by</Text><View style={s.row}><Pressable style={s.personActive}><Text>You</Text></Pressable></View><Text style={s.section}>Split</Text><View style={s.modes}>{(["EQUAL","EXACT","PERCENTAGE","SHARES"] as Mode[]).map(m=><Pressable key={m} onPress={()=>setMode(m)} style={[s.mode,mode===m&&s.modeActive]}><Text>{m}</Text></Pressable>)}</View><Text style={s.section}>Participants</Text>{people.map(p=><Pressable key={p.id} onPress={()=>setSelected(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])} style={s.participant}><Text>{selected.includes(p.id)?"✓":"○"} {p.name}</Text></Pressable>)}<View style={s.summary}>{allocations.map(a=><Text key={a.userId}>{people.find(p=>p.id===a.userId)?.name}: ₹{a.amountMinor.toString()}</Text>)}</View><Pressable disabled={!description.trim()||total<=0n||!selected.length} style={s.save}><Text style={s.saveText}>Save expense</Text></Pressable></ScrollView>
}
const s=StyleSheet.create({page:{padding:24,paddingBottom:48},title:{fontSize:30,fontWeight:"800",marginBottom:24},input:{borderWidth:1,borderRadius:16,padding:16,fontSize:17},amountLabel:{marginTop:28,fontSize:16},amount:{fontSize:48,fontWeight:"800",paddingVertical:4},section:{fontSize:15,fontWeight:"800",marginTop:24,marginBottom:10},row:{flexDirection:"row"},personActive:{padding:12,borderRadius:14,borderWidth:1},modes:{flexDirection:"row",flexWrap:"wrap",gap:8},mode:{padding:10,borderRadius:12,borderWidth:1},modeActive:{borderWidth:2},participant:{padding:14,borderBottomWidth:1},summary:{marginTop:20,padding:16,borderRadius:16},save:{marginTop:28,padding:17,borderRadius:16,alignItems:"center",borderWidth:1},saveText:{fontWeight:"800",fontSize:17}});
